spring:
  jpa:
#    show-sql: true
#    hibernate: # delete this section in future
#      ddl-auto: create-drop

  datasource:
    platform: postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

auctioneer:
  app:
    storage:
      image-path: ${IMAGE_PATH}
      file-path:  ${FILE_PATH}

#debug: true
#logging:
#  level:
#    org.springframework.security: DEBUG
