spring:
  jpa:
    show-sql: true
  datasource:
    platform: postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  storage:
    image-path: ${IMAGE_PATH}
    file-path:  ${FILE_PATH}